import type { Bank } from './types';

/**
 * Danh sách đầy đủ các ngân hàng đang hoạt động tại Việt Nam.
 * Dữ liệu được đóng băng (frozen) để tránh bị mutate ngoài ý muốn.
 */
export const banks: readonly Bank[] = Object.freeze([
  {
    brandName: 'Vietcombank',
    fullName: 'Ngân hàng TMCP Ngoại Thương Việt Nam',
    fullNameEn: 'Joint Stock Commercial Bank for Foreign Trade of Vietnam',
    type: 'Thương mại Cổ phần',
    swift: 'BFTVVNVX',
    website: 'vietcombank.com.vn',
    establishedDate: '1963-04-01',
  },
  {
    brandName: 'MBBANK',
    fullName: 'Ngân hàng TMCP Quân Đội',
    fullNameEn: 'Military Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'MSCBVNVX',
    website: 'mb.com.vn',
    establishedDate: '1994-11-04',
  },
  {
    brandName: 'VPBank',
    fullName: 'Ngân hàng TMCP Việt Nam Thịnh Vượng',
    fullNameEn: 'Vietnam Prosperity Joint Stock Commercial Bank',
    type: 'Thương mại Cổ phần',
    swift: 'VPBKVNVX',
    website: 'vpbank.com.vn',
    establishedDate: '1993-08-12',
  },
  {
    brandName: 'VietinBank',
    fullName: 'Ngân hàng TMCP Công thương Việt Nam',
    fullNameEn: 'Vietnam Joint Stock Commercial Bank of Industry and Trade',
    type: 'Thương mại Cổ phần',
    swift: 'ICBVVNVX',
    website: 'vietinbank.vn',
    establishedDate: '1988-03-26',
  },
  {
    brandName: 'Techcombank',
    fullName: 'Ngân hàng TMCP Kỹ Thương',
    fullNameEn: 'Vietnam Technological and Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'VTCBVNVX',
    website: 'techcombank.com.vn',
    establishedDate: '1993-09-27',
  },
  {
    brandName: 'BIDV',
    fullName: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam',
    fullNameEn:
      'Joint Stock Commercial Bank for Investment and Development of Vietnam',
    type: 'Thương mại Cổ phần',
    swift: 'BIDVVNVX',
    website: 'bidv.com.vn',
    establishedDate: '1957-04-26',
  },
  {
    brandName: 'Agribank',
    fullName: 'Ngân hàng NN&PT Nông thôn Việt Nam',
    fullNameEn: 'Vietnam Bank for Agriculture and Rural Development',
    type: 'Thương mại Nhà nước',
    swift: 'VBAAVNVX',
    website: 'agribank.com.vn',
    establishedDate: '1988-03-26',
  },
  {
    brandName: 'ACB',
    fullName: 'Ngân hàng TMCP Á Châu',
    fullNameEn: 'Asia Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'ASCBVNVX',
    website: 'acb.com.vn',
    establishedDate: '1993-06-04',
  },
  {
    brandName: 'HDBank',
    fullName: 'Ngân hàng TMCP Phát triển TP.HCM',
    fullNameEn: 'Ho Chi Minh City Development Joint Stock Commercial Bank',
    type: 'Thương mại Cổ phần',
    swift: 'HDBCVNVX',
    website: 'hdbank.com.vn',
    establishedDate: '1990-01-04',
  },
  {
    brandName: 'SHB',
    fullName: 'Ngân hàng TMCP Sài Gòn – Hà Nội',
    fullNameEn: 'Saigon-Hanoi Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'SHBAVNVX',
    website: 'shb.com.vn',
    establishedDate: '1993-11-13',
  },
  {
    brandName: 'VIB',
    fullName: 'Ngân hàng TMCP Quốc Tế',
    fullNameEn: 'Vietnam International Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'VNIBVNVX',
    website: 'vib.com.vn',
    establishedDate: '1996-09-18',
  },
  {
    brandName: 'MSB',
    fullName: 'Ngân hàng TMCP Hàng Hải',
    fullNameEn: 'The Maritime Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'MCOBVNVX',
    website: 'msb.com.vn',
    establishedDate: '1991-07-12',
  },
  {
    brandName: 'LPBank',
    fullName: 'Ngân hàng TMCP Lộc Phát Việt Nam',
    fullNameEn: 'Fortune Vietnam Joint Stock Commercial Bank',
    type: 'Thương mại Cổ phần',
    swift: 'LVBKVNVX',
    website: 'lpbank.com.vn',
    establishedDate: '2008-03-28',
  },
  {
    brandName: 'SeABank',
    fullName: 'Ngân hàng TMCP Đông Nam Á',
    fullNameEn: 'Southeast Asia Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'SEAVVNVX',
    website: 'seabank.com.vn',
    establishedDate: '1994-03-24',
  },
  {
    brandName: 'TPBank',
    fullName: 'Ngân hàng TMCP Tiên Phong',
    fullNameEn: 'TienPhong Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'TPBVVNVX',
    website: 'tpbank.vn',
    establishedDate: '2008-05-05',
  },
  {
    brandName: 'OCB',
    fullName: 'Ngân hàng TMCP Phương Đông',
    fullNameEn: 'Orient Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'ORCOVNVX',
    website: 'ocb.com.vn',
    establishedDate: '1996-06-10',
  },
  {
    brandName: 'VBSP',
    fullName: 'Ngân hàng Chính sách xã hội Việt Nam',
    fullNameEn: 'Vietnam Bank for Social Policies',
    type: 'Ngân hàng chính sách',
    swift: null,
    website: 'vbsp.com.vn',
    establishedDate: '2002-10-04',
  },
  {
    brandName: 'NCB',
    fullName: 'Ngân hàng TMCP Quốc dân',
    fullNameEn: 'National Citizen Bank',
    type: 'Thương mại Cổ phần',
    swift: 'NVBAVNVX',
    website: 'ncb-bank.vn',
    establishedDate: '1995-09-18',
  },
  {
    brandName: 'Sacombank',
    fullName: 'Ngân hàng TMCP Sài Gòn Tài Lộc',
    fullNameEn: 'Saigon Treasure Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'SGTTVNVX',
    website: 'sacombank.com.vn',
    establishedDate: '1991-12-21',
  },
  {
    brandName: 'Eximbank',
    fullName: 'Ngân hàng TMCP Xuất Nhập Khẩu',
    fullNameEn: 'Vietnam Export Import Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'EBVIVNVX',
    website: 'eximbank.com.vn',
    establishedDate: '1989-05-24',
  },
  {
    brandName: 'Nam A Bank',
    fullName: 'Ngân hàng TMCP Nam Á',
    fullNameEn: 'Nam A Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'NAMAVNVX',
    website: 'namabank.com.vn',
    establishedDate: '1992-10-21',
  },
  {
    brandName: 'SCB',
    fullName: 'Ngân hàng TMCP Sài Gòn',
    fullNameEn: 'Sai Gon Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'SACLVNVX',
    website: 'scb.com.vn',
    establishedDate: '2012-01-01',
  },
  {
    brandName: 'VDB',
    fullName: 'Ngân hàng Phát triển Việt Nam',
    fullNameEn: 'Vietnam Development Bank',
    type: 'Ngân hàng chính sách',
    swift: null,
    website: 'vdb.com.vn',
    establishedDate: '2006-05-19',
  },
  {
    brandName: 'Woori',
    fullName: 'Ngân hàng TNHH MTV Woori Việt Nam',
    fullNameEn: 'Woori Bank Vietnam Limited',
    type: '100% vốn nước ngoài',
    swift: 'HVBKVNVX',
    website: 'woori.com.vn',
    establishedDate: '2016-10-31',
  },
  {
    brandName: 'Vietbank',
    fullName: 'Ngân hàng TMCP Việt Nam Thương Tín',
    fullNameEn: 'Vietnam Thuong Tin Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'VNACVNVX',
    website: 'vietbank.com.vn',
    establishedDate: '2007-02-02',
  },
  {
    brandName: 'Bac A Bank',
    fullName: 'Ngân hàng TMCP Bắc Á',
    fullNameEn: 'BAC A Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'NASCVNVX',
    website: 'baca-bank.vn',
    establishedDate: '1994-09-01',
  },
  {
    brandName: 'ABBANK',
    fullName: 'Ngân hàng TMCP An Bình',
    fullNameEn: 'An Binh Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'ABBKVNVX',
    website: 'abbank.vn',
    establishedDate: '1993-05-13',
  },
  {
    brandName: 'UOB',
    fullName: 'Ngân hàng TNHH MTV UOB Việt Nam',
    fullNameEn: 'UOB Vietnam Limited',
    type: '100% vốn nước ngoài',
    swift: 'UOVBVNVX',
    website: 'uob.com.vn',
    establishedDate: '2017-09-21',
  },
  {
    brandName: 'PVcomBank',
    fullName: 'Ngân hàng TMCP Đại Chúng Việt Nam',
    fullNameEn: 'Public Vietnam Bank',
    type: 'Thương mại Cổ phần',
    swift: 'WBVNVNVX',
    website: 'pvcombank.com.vn',
    establishedDate: '2013-09-16',
  },
  {
    brandName: 'VietABank',
    fullName: 'Ngân hàng TMCP Việt Á',
    fullNameEn: 'Viet A Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'VNTTVNVX',
    website: 'vietabank.com.vn',
    establishedDate: '2003-07-04',
  },
  {
    brandName: 'HSBC',
    fullName: 'Ngân hàng TNHH MTV HSBC Việt Nam',
    fullNameEn: 'HSBC Bank Vietnam Limited',
    type: '100% vốn nước ngoài',
    swift: 'HSBCVNVX',
    website: 'hsbc.com.vn',
    establishedDate: '2008-09-08',
  },
  {
    brandName: 'PBVN',
    fullName: 'Ngân hàng TNHH MTV Public Bank Việt Nam',
    fullNameEn: 'Public Bank Vietnam Limited',
    type: '100% vốn nước ngoài',
    swift: 'VIDPVNV5',
    website: 'pbvn.com.vn',
    establishedDate: '2016-03-24',
  },
  {
    brandName: 'SCBVL',
    fullName: 'Ngân hàng TNHH MTV Standard Chartered Việt Nam',
    fullNameEn: 'Standard Chartered Bank Vietnam Limited',
    type: '100% vốn nước ngoài',
    swift: 'SCBLVNVX',
    website: 'scbvl.com.vn',
    establishedDate: '2008-09-08',
  },
  {
    brandName: 'PGBank',
    fullName: 'Ngân hàng TMCP Thịnh vượng và Phát triển',
    fullNameEn: 'Prosperity and Growth Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'PGBLVNVX',
    website: 'pgbank.com.vn',
    establishedDate: '1993-11-13',
  },
  {
    brandName: 'BVBank',
    fullName: 'Ngân hàng TMCP Bản Việt',
    fullNameEn: 'Viet Capital Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'VCBCVNVX',
    website: 'bvbank.net.vn',
    establishedDate: '1992-12-25',
  },
  {
    brandName: 'Kienlongbank',
    fullName: 'Ngân hàng TMCP Kiên Long',
    fullNameEn: 'Kien Long Commercial Joint Stock Bank',
    type: 'Thương mại Cổ phần',
    swift: 'KLBKVNVX',
    website: 'kienlongbank.com',
    establishedDate: '1995-10-27',
  },
  {
    brandName: 'SHBVN',
    fullName: 'Ngân hàng TNHH MTV Shinhan Việt Nam',
    fullNameEn: 'Shinhan Bank Vietnam Limited',
    type: '100% vốn nước ngoài',
    swift: 'SHBKVNVX',
    website: 'shbvn.com.vn',
    establishedDate: '2008-12-29',
  },
  {
    brandName: 'ANZVL',
    fullName: 'Ngân hàng TNHH MTV ANZ Việt Nam',
    fullNameEn: 'ANZ Bank Vietnam Limited',
    type: '100% vốn nước ngoài',
    swift: 'ANZBVNVX',
    website: 'anzvl.com.vn',
    establishedDate: '2008-10-09',
  },
  {
    brandName: 'CIMB',
    fullName: 'Ngân hàng TNHH MTV CIMB Việt Nam',
    fullNameEn: 'CIMB Bank Vietnam Limited',
    type: '100% vốn nước ngoài',
    swift: 'CIBBVNVN',
    website: 'cimb.com.vn',
    establishedDate: '2016-08-31',
  },
  {
    brandName: 'SAIGONBANK',
    fullName: 'Ngân hàng TMCP Sài Gòn Công Thương',
    fullNameEn: 'Saigon Bank for Industry & Trade',
    type: 'Thương mại Cổ phần',
    swift: 'SBITVNVX',
    website: 'saigonbank.com.vn',
    establishedDate: '1987-10-16',
  },
  {
    brandName: 'HLBVN',
    fullName: 'Ngân hàng TNHH MTV Hong Leong Việt Nam',
    fullNameEn: 'Hong Leong Bank Vietnam Limited',
    type: '100% vốn nước ngoài',
    swift: 'HLBBVNVX',
    website: 'hlbvn.com.vn',
    establishedDate: '2008-12-29',
  },
  {
    brandName: 'IVB',
    fullName: 'Ngân hàng TNHH Indovina',
    fullNameEn: 'Indovina Bank Ltd.',
    type: 'Ngân hàng Liên doanh',
    swift: 'IABBVNVX',
    website: 'ivb.com.vn',
    establishedDate: '1990-01-21',
  },
  {
    brandName: 'BAOVIET Bank',
    fullName: 'Ngân hàng TMCP Bảo Việt',
    fullNameEn: 'Bao Viet Joint Stock Commercial Bank',
    type: 'Thương mại Cổ phần',
    swift: 'BVBVVNVX',
    website: 'baovietbank.vn',
    establishedDate: '2009-01-14',
  },
  {
    brandName: 'VRB',
    fullName: 'Ngân hàng Liên doanh Việt Nga',
    fullNameEn: 'Vietnam Russia Joint Venture Bank',
    type: 'Ngân hàng Liên doanh',
    swift: 'VRBAVNVX',
    website: 'vrb.com.vn',
    establishedDate: '2006-11-19',
  },
  {
    brandName: 'Co-opBank',
    fullName: 'Ngân hàng Hợp tác xã Việt Nam',
    fullNameEn: 'Co-operative Bank of Vietnam',
    type: 'NH Hợp tác xã',
    swift: null,
    website: 'co-opbank.com.vn',
    establishedDate: '2013-07-01',
  },
  {
    brandName: 'GPBank',
    fullName: 'Ngân hàng TNHH MTV Kỷ Nguyên Thịnh Vượng',
    fullNameEn:
      'Generation of Prosperity Sole Member Limited Commercial Bank',
    type: 'TNHH MTV',
    swift: 'GBNKVNVX',
    website: 'gpbank.com.vn',
    establishedDate: '1993-11-13',
  },
  {
    brandName: 'VCBNeo',
    fullName: 'Ngân hàng TNHH MTV Ngoại thương Công nghệ số',
    fullNameEn: 'Vietcombank Neo Limited',
    type: 'TNHH MTV',
    swift: 'GTBAVNVX',
    website: 'vcbneo.com.vn',
    establishedDate: '1989-09-01',
  },
  {
    brandName: 'Vikki Bank',
    fullName: 'Ngân hàng TNHH MTV Số Vikki',
    fullNameEn: 'Vikki Digital Bank Limited',
    type: 'TNHH MTV',
    swift: 'EACBVNVX',
    website: 'vikkibank.vn',
    establishedDate: '1992-07-01',
  },
  {
    brandName: 'MBV',
    fullName: 'Ngân hàng TNHH MTV Việt Nam Hiện Đại',
    fullNameEn: 'Modern Bank of Vietnam Limited',
    type: 'TNHH MTV',
    swift: 'OJBAVNVX',
    website: 'mbv.com.vn',
    establishedDate: '1993-12-30',
  },
]);